name = "controlstackai-api"
main = "src/index.js"
compatibility_date = "2024-11-06"

[[d1_databases]]
binding = "DB"
database_name = "controlstackai-db"
database_id = "REPLACE_WITH_YOUR_D1_ID"

[vars]
SERVICE_TOKEN = "replace-with-strong-random"
