name = "controlstackai-api"
main = "src/index.ts"
compatibility_date = "2025-09-25"

[vars]
CORS_ALLOW_ORIGIN = "https://controlstackai.com"
# Non-secret config (secrets should be set with `wrangler secret put`):
MAIL_FROM = "matthew@mangano-consulting.com"
MAIL_TO = "matthew@mangano-consulting.com"
TURNSTILE_SITE_KEY = ""

[observability]
enabled = true

[[env.staging.d1_databases]]
binding = "DB"                          # must match env.DB in your Worker code
database_name = "controlstackai_db_staging"
database_id = "f962ada1-7ce8-4459-a5bb-c02ea75f6f9e"

[env.staging.vars]
CORS_ALLOW_ORIGIN = "https://controlstackai.com"
MAIL_FROM = "matthew@mangano-consulting.com"
MAIL_TO = "matthew@mangano-consulting.com"
TURNSTILE_SITE_KEY = ""

[env.production]
# other prod vars...
[[env.production.d1_databases]]
binding = "DB"
database_name = "controlstackai_db_prod"
database_id = "e306ed22-2253-41bc-82a0-a06e93f3daaa"
